### ISSUE TITLE
int64 values are being parsed as floats instead of strings

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#53]
See #47 for context.

e.g. a value of `"manifest" "6404082971767543753"`

**Comment by erri120** [comment]
Would it be viable to add a `public readonly string OriginalText` field to allow consumers to do custom parsing? This way, the lib can try to parse the original text value, but consumers would still have the option to access that original value.

After all, this library can only guess what type a value should have, while the consumer _expects_ a certain type.

**Comment by xPaw** [comment]
Ideally, the bug with converting them to floats should be fixed, so the conversion logic matches Valve's own behaviour.

And realistically it should be able to correctly to assign to `ulong` if that's what the consumer's property type is.

I did have an idea to add an option to turn off type guessing, but that's just working around the issue.

**Comment by xPaw** [comment]
Valve's behaviour comes from their keyvalues.cpp code from the Source engine. They obviously don't provide any documentation for the format.

We're matching their behaviour, because whether you like it or not, it's their "proprietary" format, and we're trying to match how their parser works.

I'm not gonna say that type guessing is great. Ideally we wouldn't care to guess the types, and instead correctly support converting types to whatever property types the consumer is using.

**Comment by erri120** [comment]
> We're matching their behaviour, because whether you like it or not, it's their "proprietary" format, and we're trying to match how their parser works.

Yes, it's a proprietary format and this open-source library tries to parse it correctly. However, I'm arguing that type guessing shouldn't be part of **this** parser. The parser should read the file, character by character, and produce language-specific constructs, based on the input. In our case, those constructs are `KVObject` and `KVObjectValue<T>`. As detailed previously, the text format only contains string values, so **this** parser should only produce string values.

Type-guessing is something Valve does because they need it or have needed it internally for something. I don't want to say the Source Engine isn't a great _source_ for this, but the [wiki article](https://developer.valvesoftware.com/wiki/KeyValues) about this hasn't seen much change since [2006](https://developer.valvesoftware.com/w/index.php?title=KeyValues&action=history).

> Types are also important when (de)serializing to the binary format, which actually stores the type.

When serializing to the binary format, you're using a class, right? A class with C# types like shown in the [README](https://github.com/SteamDatabase/ValveKeyValue#serializing-to-binary)? Again, type guessing doesn't matter because what the library **guessed** can be different to what the consumer **expects**.

If you were to read a text format and serialize the `KVObject` to binary in a direct conversion without having some model/DTO class in the middle, type guessing might be useful. However, at that point you should move type guessing to the binary serialization of `KVObjectValue<string>` instead of having it in the text parser.

> I'm not gonna say that type guessing is great. Ideally we wouldn't care to guess the types, and instead correctly support converting types to whatever property types the consumer is using.

That's the point. Parse **all** values as `KVObjectValue<string>` and don't do type guessing. The consumer doesn't see the difference because all they get is an instance of `KVValue` with `ToX` methods to convert to whatever **they need**.

**Comment by yaakov-h** [comment]
> When serializing to the binary format, you're using a class, right?

Not necessarily.

https://github.com/SteamDatabase/ValveKeyValue/blob/master/ValveKeyValue/ValveKeyValue.Test/Binary/BinaryObjectSerializationTestCase.cs#L12-L21

What @xPaw stated is correct. Valve do not provide any kind of spec, but we try to stay as faithful as we can to their implementation as the canonical / reference implementation so that we don't have compatibility issues or strange divergences.

Sometimes Valve produce KV files in different products that require different parsing rules, or have bugs that they haven't noticed, which requires us to add options such as #43 so that we can continue parsing their data files without causing problems elsewhere

The type-guessing behaviour comes from Valve. Clearly we have some difference in our implementation that needs to be resolved, I just haven't had the time yet to step through them myself and see what the difference is:

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/tier1/KeyValues.cpp#L2339-L2399

As an aside, some of the test cases you've changed in #75 will end up as breaking changes, because the type-guesser parsing code and the IConvertible conversions are not identical.

**Comment by erri120** [comment]
Added an option as a compromise #76.
