### ISSUE TITLE
VBKV

### ISSUE THREAD

**Issue by SinZ163** [SteamDatabase/ValveKeyValue#9]
Appears to be a wrapper to normal Binary KeyValues, with a header and a changed end byte

see ValvePython/vdf#11

**Comment by CitadelCore** [comment]
Implementation of this should be pretty easy, what I've done is added a `HasVbkvHeader` property to `KVSerializerOptions` and a few things:

- code in `KV1BinaryReader` to read the 0x0B header instead of 0x08, calculate the CRC32 of the body after reading and compare it to the one in the header; if it doesn't match we throw a `KeyValueException`
- code in `KV1BinarySerializer` to write the 0x0B header instead of 0x08, and to calculate the CRC32 checksum of the serialised body after serialisation and to store it in the header

Should be able to use the Crc32.NET nuget package for calculating the checksum - it's licensed under MIT: https://github.com/force-net/Crc32.NET

**Comment by xPaw** [comment]
> Should be able to use the Crc32.NET nuget package for calculating the checksum

CRC32 is easy enough that we can directly add code in the repo without pulling a package.

**Comment by CitadelCore** [comment]
Yep, should likely just pull the Crc32 class from here: https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/Utils/Crc32.cs

**Comment by xPaw** [comment]
I was looking at this for VRF: https://github.com/SteamDatabase/ValveResourceFormat/commit/cc00c0cf230c104f9d3a1917ba6c1cb971df1b54

The only problem is the alternative end byte.
